### PR TITLE
[scripts] Introduce scripts/fetch-toolchains.py

### PR DESCRIPTION
**Pull request by joshuaseaton**
This change introduces $LK_ROOT/toolchains as an official installation directory for toolchains, as well as a new script for conveniently installing them there. getting_started.md is updated to suggest its use.

### CODE REVIEW

**Comment by joshuaseaton** [comment]
What do you think of updating CI to use this as well?

**Comment by travisg** [comment]
> What do you think of updating CI to use this as well?

I'd like to nak that, because the CI explicitly pulls down what versions it needs, and only exactly what it needs for a specific build. Also it uses the github cache action which saves it from pulling more than once for any given roll.

**Comment by joshuaseaton** [comment]
Fair enough! The needs for CI are certainly different than for devs (e.g., around caching). (This was the classic tension on Fuchsia around sentiments and filed bugs that would amount to "can't you just use fx in automation??")

**Comment by travisg** [comment]
Looks like there's a problem, at least with --list, where it's finding the highest single digit one (ie, 8.2.0, etc) instead of a double digit (ie, 14)

**Comment by joshuaseaton** [comment]
Ah, thanks for catching that. I was doing a naive strcmp on the version string, rather than a lexicographic comp on the actual int tokens. Fixed

**Review by travisg — APPROVED** [review]
Looks good, seems to work fine here on ubuntu 24.04 and mac with python 3.12. It may not work right on older pythons, but i'm not particularly worried about that right now unless it becomes a problem.

**Pull request merged**
