### PR TITLE
[target] Add target for NextCoinP0

### PR DESCRIPTION
**Pull request by hollanderic**
Support for NextCoinP0 - mainly a copied subset of dartuinoP0

### CODE REVIEW

**Comment by travisg** [comment]
Looks generally okay, I'd name it target/nextcoin personally. P0 vs P1 vs P2 and whatnot is probably a project level #define and/or hardware revision bits.

**Comment by travisg** [comment]
If this is getting rolled up into the demo branch, which I assume will get merged in once the demo stuff is over, then go ahead and close it here.

**Comment by nvll** [comment]
Demo branch is full of too many wips, we'll have to clean up and cherry
pick things over to master.

**Comment by travisg** [comment]
Is this going here or did you guys push it to the other repo?

**Comment by travisg** [comment]
What do you guys want to do with this one?

**Comment by nvll** [comment]
I'd vote abandon for the time being so we don't add a mostly untestable
target.

**Comment by travisg** [comment]
going to abandon this for now.

**Pull request closed without merging**
