### PR TITLE
Project: add platform/target/project support of mt6735

### PR DESCRIPTION
**Pull request by macpaul**
These set of patches were originated from platform and project mt6797 which commited by Mediatek.

According to the source release from vendor “Raindi Technology"(http://www.raindi.com.cn/), you can buy development board of mt6735 from Taobao (https://world.taobao.com/item/539050522155.htm) and get the reference SDK.

Hence I'm trying to port development board "Project: ap7350_65u_l1" of platform mt6735 from the following release back to mainline of little kernel.
http://git.huayusoft.com/tomsu/AP7350_MDK-kernel
https://github.com/alexgoussev/AP7350_MDK-kernel

While this board and the platform is a famous low-end product, to get support in the mainline little kernel will be good to all developers.

### CODE REVIEW

**Comment by travisg** [comment]
looks good, can you reword the commits and prefix [mt6735] or some other indicator what platform/target each of the commits are for? See LK history log for examples.

**Comment by macpaul** [comment]
This is strange, I've add prefix include [platform/target/mt6735] in local git by "git commit --amend".
After I pushed to github, these prefix seems go disappeared. I'll try to get them back in the pull-request.
Can I simply edit them in github?

**Comment by travisg** [comment]
yeah you needed to do the rebase i guess.

**Comment by abyss10** [comment]
Anybody help in in getting touchpanel GT9157 for my device Micromax Q372 actually I don't have sources and collecting drivers, please help

**Pull request merged**
