### PR TITLE
Pr/portgroup add rem

### PR DESCRIPTION
**Pull request by gkalsi**
Add an API to dynamically add/remove ports from a port group.

### CODE REVIEW

**Comment by gkalsi** [comment]
Updated as per @cpu-chromium's comments. 

It turns out that adding a port to a port group twice is already impossible because once a read port is bound to a port group, it cannot be added to a port group again.

Note that this does not preclude opening two different ports with the same name and adding them to the same port group.

**Comment by gkalsi** [comment]
@cpu-chromium Do my most recent changes look okay? Clear to merge?

**Comment by cpizano** [comment]
Go ahead.

**Comment by gkalsi** [comment]
Merged.

**Pull request closed without merging**
