### PR TITLE
[arch][arm] fix disabling WITH_KERNEL_VM

### PR DESCRIPTION
**Pull request by M1cha**
inspired by the commit from @xiaoxiang-xiaomi but without disabling the MMU

### CODE REVIEW

**Comment by zeusk** [comment]
what's the point of using mmu without vm ?

**Comment by travisg** [comment]
You have to use it to at least set up an identity map with different cache
settings on main memory and device memory before you can enable the data
cache. That's what the old mmu code on lk used to do prior to the VM. It
could only handle 1MB segments.

**Comment by M1cha** [comment]
didn't the novm commits fix this?

**Comment by travisg** [comment]
It might have. I have been thinking of revisiting this soon. There is some new mmu stuff coming down the pipe soon, to fully support user space, and I figured I'd look at it then.

**Comment by M1cha** [comment]
I'm not sure if this was fixed on main, but given how much LK evolved this change probably doesn't make sense anymore.

**Pull request closed without merging**
