### PR TITLE
[kernel] Add debug tracking of stack memory usage.

### PR DESCRIPTION
**Pull request by konkers**
See question on line 975.

### CODE REVIEW

**Comment by travisg** [comment]
This seems pretty fine. Just a nit and LGTM.

**Comment by konkers** [comment]
Boo github drops comments from previous patch versions........

**Comment by M1cha** [comment]
@konkers in github, comments are tied to a commit id, if u rebase, that id changes. if u know the sha1 u can still see the comments ;)

**Comment by travisg** [comment]
LGTM

**Comment by travisg** [comment]
rebased and pushed into mainline

**Pull request closed without merging**
