### PR TITLE
read only fat32 driver with long filename support.

### PR DESCRIPTION
**Pull request by pablomarx**

### CODE REVIEW

**Comment by travisg** [comment]
Looks interesting, who's Steve White? Was this for some internal project?

**Comment by pablomarx** [comment]
I'm Steve.  It was written for some Raspberry Pi projects, since they boot off a FAT partition – handy to read other files located on that partition.

Specifically, it was for a rewrite of a bare metal port of Squeak.  I've long had a very crude version of this, but thought it'd be nice to host it on a clean code base (lk), and gain easy ability to get it running on other ARM SBCs (Beaglebone, etc).  And for that project, it needs to read the Squeak image and source files from the boot partition, hence this FAT code.

I have a lot of other RPI code (DMA, EMMC, etc) that I'm trying to clean up and get PR'ed in the near future.

**Comment by travisg** [comment]
Oh neat. Looks pretty good, I'll test the merge against mainline and push it in if everything works fine. Some of the FS layer changed recently, so there may need to be a few tweaks.

**Comment by travisg** [comment]
Looks good, going to roll it in and run a LK formatting tool across it if you dont mind. It'll bump the indents up to 4, but will also make sure all the indents are spaces and whatnot.

**Comment by travisg** [comment]
Pushed into mainline. Thanks!

**Pull request closed without merging**
